# Makefile : Compile jobshop.cc

all:	jobshop.cc
	g++ -g -o jobshop jobshop.cc -Wno-deprecated -I ./galib247 -L ./galib247/ga -lga
	#g++ -o jobshop jobshop.cc -Wno-deprecated -lcurses -I ./galib247 -L ./galib247/ga -lga
clean:
	rm -f Queens
