/*
 * Copyright 2014 Peter Lacko
 * 
 */
package xlacko06.sfc.ga.gui;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import xlacko06.sfc.ga.func.GeneticAlgorithm;
import xlacko06.sfc.ga.func.Item;

/**
 *
 * @author peterson
 */
public class GAConfigUI extends javax.swing.JFrame {

	
	private ArrayList<Item> knapsack;
	private int maxKnapsackVolume;
	/**
	 * Creates new form GAConfigUI
	 */
	public GAConfigUI() {
		super("Genetic Algorithm Demonstration");
		knapsack = new ArrayList<>();
		generateKnapsack();
		initComponents();
		SimpleAttributeSet attribs = new SimpleAttributeSet();
		StyleConstants.setAlignment(attribs , StyleConstants.ALIGN_RIGHT);
		jTextPane1.setParagraphAttributes(attribs, true);
		jTextPane2.setParagraphAttributes(attribs, true);
		jTextPane3.setParagraphAttributes(attribs, true);
		jTextPane1.setText("1.\n2.\n3.\n4.\n5.\n6.\n7.\n8.");
		jLabel2.setText("Max objem knapsacku: " + maxKnapsackVolume);
		drawKnapsack();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jScrollPane6 = new javax.swing.JScrollPane();
                jTextItems2 = new javax.swing.JTextPane();
                jPanel1 = new javax.swing.JPanel();
                lblRecombinationPoints = new javax.swing.JLabel();
                lblRecombinaitontype = new javax.swing.JLabel();
                btnConfirm = new javax.swing.JButton();
                lblParantSelection = new javax.swing.JLabel();
                selRecombinationType = new javax.swing.JComboBox();
                btnCancel = new javax.swing.JButton();
                selParentSelection = new javax.swing.JComboBox();
                lblPopulationSize = new javax.swing.JLabel();
                lblReproductionCycles = new javax.swing.JLabel();
                sldPopulationSize = new javax.swing.JSlider();
                sldReproductionCycles = new javax.swing.JSlider();
                sldReinsertion = new javax.swing.JSlider();
                lblReinsertionValue = new javax.swing.JLabel();
                lblPopulationSizeValue = new javax.swing.JLabel();
                lblReproductionCyclesValue = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jButtonGenKnapsack = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextPane1 = new javax.swing.JTextPane();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextPane2 = new javax.swing.JTextPane();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextPane3 = new javax.swing.JTextPane();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();

                jTextItems2.setEditable(false);
                jTextItems2.setBackground(new java.awt.Color(204, 204, 204));
                jTextItems2.setBorder(null);
                jTextItems2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
                jScrollPane6.setViewportView(jTextItems2);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nastavenie genetického algoritmu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 10))); // NOI18N

                lblRecombinationPoints.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblRecombinationPoints.setText("Body rekombinácie:");

                lblRecombinaitontype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblRecombinaitontype.setText("Počet nahradení:");

                btnConfirm.setText("Start simulation");
                btnConfirm.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnConfirmActionPerformed(evt);
                        }
                });

                lblParantSelection.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblParantSelection.setText("Výber rodiča:");

                selRecombinationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "One point", "Two points", "Three points", "Uniform" }));

                btnCancel.setText("Exit program");
                btnCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCancelActionPerformed(evt);
                        }
                });

                selParentSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Roulette wheel", "Elite selection", "Tournament selection" }));
                selParentSelection.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selParentSelectionActionPerformed(evt);
                        }
                });

                lblPopulationSize.setText("Veľkosť populácie:");

                lblReproductionCycles.setText("Počet cyklov reprodukcie:");

                sldPopulationSize.setMajorTickSpacing(1);
                sldPopulationSize.setMaximum(10);
                sldPopulationSize.setMinimum(2);
                sldPopulationSize.setMinorTickSpacing(1);
                sldPopulationSize.setSnapToTicks(true);
                sldPopulationSize.setToolTipText("");
                sldPopulationSize.setValue(4);
                sldPopulationSize.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                sldPopulationSizeStateChanged(evt);
                        }
                });

                sldReproductionCycles.setMaximum(50);
                sldReproductionCycles.setMinimum(1);
                sldReproductionCycles.setValue(10);
                sldReproductionCycles.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                sldReproductionCyclesStateChanged(evt);
                        }
                });

                sldReinsertion.setMajorTickSpacing(1);
                sldReinsertion.setMaximum(10);
                sldReinsertion.setMinimum(1);
                sldReinsertion.setMinorTickSpacing(1);
                sldReinsertion.setSnapToTicks(true);
                sldReinsertion.setValue(2);
                sldReinsertion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                sldReinsertion.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                sldReinsertionStateChanged(evt);
                        }
                });

                lblReinsertionValue.setText("2");

                lblPopulationSizeValue.setText("4");

                lblReproductionCyclesValue.setText("10");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblParantSelection)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(59, 59, 59)
                                                                        .addComponent(lblPopulationSize))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(11, 11, 11)
                                                                        .addComponent(lblReproductionCycles)))
                                                        .addComponent(lblRecombinationPoints))
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(selParentSelection, javax.swing.GroupLayout.Alignment.LEADING, 0, 201, Short.MAX_VALUE)
                                                                .addComponent(selRecombinationType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(sldReproductionCycles, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                                                        .addComponent(sldPopulationSize, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblPopulationSizeValue)
                                                                        .addComponent(lblReproductionCyclesValue)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnCancel)
                                                                .addGap(34, 34, 34))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lblRecombinaitontype)
                                                                .addGap(42, 42, 42)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnConfirm)
                                                        .addComponent(sldReinsertion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblReinsertionValue)))
                                .addContainerGap(28, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblPopulationSize)
                                                        .addComponent(sldPopulationSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblPopulationSizeValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblReproductionCycles)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblParantSelection)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRecombinationPoints)
                                                .addGap(36, 36, 36))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sldReproductionCycles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblReproductionCyclesValue))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(selParentSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(selRecombinationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(lblReinsertionValue)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblRecombinaitontype)
                                                        .addComponent(sldReinsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnConfirm)
                                                        .addComponent(btnCancel))
                                                .addGap(26, 26, 26))))
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Knapsack problém", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andale Mono", 1, 10))); // NOI18N

                jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel2.setText("Knapsack o objeme:");

                jButtonGenKnapsack.setText("Vygeneruj nový obsah");
                jButtonGenKnapsack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonGenKnapsackActionPerformed(evt);
                        }
                });

                jLabel3.setBackground(new java.awt.Color(153, 255, 153));
                jLabel3.setText("Položka");

                jLabel4.setText("Objem");

                jLabel5.setText("Hodnota");

                jScrollPane1.setBackground(new java.awt.Color(204, 0, 204));
                jScrollPane1.setBorder(null);
                jScrollPane1.setFocusable(false);

                jTextPane1.setEditable(false);
                jTextPane1.setBorder(null);
                jTextPane1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jTextPane1.setFocusable(false);
                jScrollPane1.setViewportView(jTextPane1);

                jScrollPane2.setBackground(new java.awt.Color(204, 0, 204));
                jScrollPane2.setBorder(null);
                jScrollPane2.setFocusable(false);

                jTextPane2.setEditable(false);
                jTextPane2.setBorder(null);
                jTextPane2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jScrollPane2.setViewportView(jTextPane2);

                jScrollPane3.setBackground(new java.awt.Color(204, 0, 204));
                jScrollPane3.setBorder(null);
                jScrollPane3.setFocusable(false);

                jTextPane3.setEditable(false);
                jTextPane3.setBorder(null);
                jTextPane3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
                jScrollPane3.setViewportView(jTextPane3);

                jTextArea1.setEditable(false);
                jTextArea1.setBackground(new java.awt.Color(153, 255, 153));
                jTextArea1.setColumns(19);
                jTextArea1.setRows(5);
                jTextArea1.setText("Knapsack problém je úloha,\nkde máme k dispozícii určité\nmnožstvo položiek, každú\ns určitým objemom a hodnotou,\na knapsack kam chceme tieto\npoložky uložiť. Cieľom je vybrať\ntaké položky aby ich celkový\nobjem nebol vačší ako objem\nknapsacku a v súčte mali\nčo najvyššiu možnú hodnotu.");
                jTextArea1.setBorder(null);
                jTextArea1.setFocusable(false);
                jTextArea1.setOpaque(false);
                jScrollPane4.setViewportView(jTextArea1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jButtonGenKnapsack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel4)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(jLabel5))))
                                .addGap(0, 23, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 29, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonGenKnapsack))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane4))
                                .addGap(16, 16, 16))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void selParentSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selParentSelectionActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_selParentSelectionActionPerformed

        private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
		GeneticAlgorithm ga = new GeneticAlgorithm();
		ga.setPopulationSize(sldPopulationSize.getValue());
		ga.setReproductionCycles(sldReproductionCycles.getValue());
		ga.setParentSelection(selParentSelection.getSelectedIndex());
		ga.setRecombinationType(selRecombinationType.getSelectedIndex());
		ga.setReinsertion(sldReinsertion.getValue());
		ga.initPopulation(knapsack, maxKnapsackVolume);
		ga.performCycle();
		GASimulationUI simFrame = new GASimulationUI();
		simFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		simFrame.setVisible(true);
		simFrame.myInit(ga);
        }//GEN-LAST:event_btnConfirmActionPerformed

        private void sldReinsertionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldReinsertionStateChanged
		lblReinsertionValue.setText(Integer.toString(sldReinsertion.getValue()));
        }//GEN-LAST:event_sldReinsertionStateChanged

        private void sldPopulationSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPopulationSizeStateChanged
		lblPopulationSizeValue.setText(Integer.toString(sldPopulationSize.getValue()));
        }//GEN-LAST:event_sldPopulationSizeStateChanged

        private void sldReproductionCyclesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldReproductionCyclesStateChanged
		lblReproductionCyclesValue.setText(Integer.toString(sldReproductionCycles.getValue()));
        }//GEN-LAST:event_sldReproductionCyclesStateChanged

        private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		System.exit(0);
        }//GEN-LAST:event_btnCancelActionPerformed

        private void jButtonGenKnapsackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenKnapsackActionPerformed
		generateKnapsack();
		drawKnapsack();
		jLabel2.setText("Max. objem knapsacku: " + maxKnapsackVolume);
        }//GEN-LAST:event_jButtonGenKnapsackActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GAConfigUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GAConfigUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GAConfigUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GAConfigUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GAConfigUI().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCancel;
        private javax.swing.JButton btnConfirm;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton jButtonGenKnapsack;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane6;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextPane jTextItems2;
        private javax.swing.JTextPane jTextPane1;
        private javax.swing.JTextPane jTextPane2;
        private javax.swing.JTextPane jTextPane3;
        private javax.swing.JLabel lblParantSelection;
        private javax.swing.JLabel lblPopulationSize;
        private javax.swing.JLabel lblPopulationSizeValue;
        private javax.swing.JLabel lblRecombinaitontype;
        private javax.swing.JLabel lblRecombinationPoints;
        private javax.swing.JLabel lblReinsertionValue;
        private javax.swing.JLabel lblReproductionCycles;
        private javax.swing.JLabel lblReproductionCyclesValue;
        private javax.swing.JComboBox selParentSelection;
        private javax.swing.JComboBox selRecombinationType;
        private javax.swing.JSlider sldPopulationSize;
        private javax.swing.JSlider sldReinsertion;
        private javax.swing.JSlider sldReproductionCycles;
        // End of variables declaration//GEN-END:variables

	private void generateKnapsack() {
		Item x;
		knapsack.clear();
		for (int i = 0; i < 8; i++) {
			x = new Item();
			knapsack.add(x);
		}
		maxKnapsackVolume = 0;
		for (Item i:knapsack) {
			maxKnapsackVolume += 128 + (int)i.getVolume();
		}
		maxKnapsackVolume /= 2;
	}

	private void drawKnapsack() {
		String vol = "";
		String val = "";
		for (Item i: knapsack) {
			vol+= Integer.toString((int)(i.getVolume())+128) + " \n";
			val+= Integer.toString((int)(i.getValue())+128) + " \n";
		}
		vol = vol.substring(0, vol.length()-1);
		val = val.substring(0, val.length()-1);
		jTextPane2.setText(vol);
		jTextPane3.setText(val);
	}
}
